module.exports = function(RED) {
  'use strict';

  const mqtt = require('../../put-mqtt/mqtt.js');


  function PutMqttCommandNode(n){
    RED.nodes.createNode(this, n);
    const node = this;
    node.command = n.command;
    node.mqtt = mqtt.get();

    node.on('input', function(msg){
      const context = node.context();
      const offline_mode = context.global.get('offline_mode');
      // const debug_mode = context.global.get('debug_mode');
      const tester_id = context.global.get('tester_id');
      const tester = node.topic || context.global.get('tester');

      if(offline_mode){
        node.send([null, msg]);

      }else{
        if(typeof(msg.payload) != 'object'){
          node.error('msg.payload is not an object', msg);
          return;

        }

        const payload = {
          ...msg.payload,
          cmd: node.command,
          // msg_id is generated by mqtt.request(...)
        };
        // mqtt.sanitize(payload);

        mqtt.request(`${tester.toLowerCase()}/${tester_id}/cmd`, payload, function(err, msgout){
          msg.payload = msgout;
          if(err){
            node.send([msg, null]);

          }else{
            node.send([null, msg]);

          }

        }, node, false, `${tester.toLowerCase()}/${tester_id}/cmd_result`);

      }

    });


    node.on('close', function(done){
      if(mqtt){
        mqtt.close(done);
      }else{
        done();
      }
    });

  }
  RED.nodes.registerType('put mqtt command', PutMqttCommandNode);

}
